apiVersion: v1
kind: Service
metadata:
  labels:
    app: n1
  name: n1
  namespace: n1
spec:
  clusterIP: 10.233.61.66
  clusterIPs:
  - 10.233.61.66
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30407
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
